// AI Weekly Edge Report
//
// Turns the analytics Blipyy already computes into a proactive weekly
// coaching report: "here's your edge and your leak this week." The structured
// report is deterministic; the narrative is generated by the USER'S configured
// AI provider when available and falls back to a template otherwise. AI
// failure never blocks report generation.
//
// All report fields use snake_case (project standard for stored/API data).

const db = require('../config/database');
const TradeQueries = require('./tradeQueries');
const AIService = require('../utils/aiService');
const EmailService = require('./emailService');
const User = require('../models/User');

const MIN_GROUP_TRADES = 2;
const LOSS_STREAK_THRESHOLD = 3;
const OVERSIZED_LOSER_RATIO = 1.5;

function toDateString(date) {
  return date.toISOString().split('T')[0];
}

function shiftDays(dateStr, days) {
  const d = new Date(`${dateStr}T00:00:00Z`);
  d.setUTCDate(d.getUTCDate() + days);
  return toDateString(d);
}

function round2(value) {
  const num = parseFloat(value);
  if (!Number.isFinite(num)) return 0;
  return Math.round(num * 100) / 100;
}

function formatMoney(value) {
  const num = round2(value);
  const abs = Math.abs(num).toFixed(2);
  return num < 0 ? `-$${abs}` : `$${abs}`;
}

function formatHourLabel(hour) {
  const h = parseInt(hour, 10);
  if (!Number.isFinite(h)) return 'unknown';
  const suffix = h >= 12 ? 'PM' : 'AM';
  const display = h % 12 === 0 ? 12 : h % 12;
  return `${display}:00 ${suffix}`;
}

class EdgeReportService {
  // Most recently completed Monday-Sunday week relative to `now`.
  // Run on Monday pre-market this covers the prior Mon-Sun.
  static getDefaultPeriod(now = new Date()) {
    const day = now.getUTCDay(); // 0 = Sunday
    const daysSinceSunday = day === 0 ? 7 : day;
    const periodEnd = shiftDays(toDateString(now), -daysSinceSunday);
    const periodStart = shiftDays(periodEnd, -6);
    return { periodStart, periodEnd };
  }

  static summarizeAnalytics(analytics) {
    const summary = analytics?.summary || {};
    return {
      total_trades: parseInt(summary.totalTrades) || 0,
      winning_trades: parseInt(summary.winningTrades) || 0,
      losing_trades: parseInt(summary.losingTrades) || 0,
      win_rate: round2(summary.winRate),
      total_pnl: round2(summary.totalPnL),
      profit_factor: round2(summary.profitFactor),
      avg_win: round2(summary.avgWin),
      avg_loss: round2(summary.avgLoss)
    };
  }

  // Per-strategy / per-symbol / per-entry-hour aggregates for the week.
  // Kept to three tiny grouped queries; everything else reuses
  // TradeQueries.getAnalytics.
  static async getDimensionStats(userId, periodStart, periodEnd) {
    const baseWhere = `
      WHERE t.user_id = $1
        AND t.trade_date >= $2::date
        AND t.trade_date <= $3::date
        AND t.exit_price IS NOT NULL
        AND t.pnl IS NOT NULL
    `;
    const params = [userId, periodStart, periodEnd];

    const [strategyResult, symbolResult, hourResult] = await Promise.all([
      db.query(`
        SELECT COALESCE(NULLIF(TRIM(t.strategy), ''), 'unspecified') AS name,
               COUNT(*)::integer AS trades,
               SUM(t.pnl) AS total_pnl,
               COUNT(*) FILTER (WHERE t.pnl > 0)::integer AS wins
        FROM trades t
        ${baseWhere}
        GROUP BY 1
      `, params),
      db.query(`
        SELECT t.symbol AS name,
               COUNT(*)::integer AS trades,
               SUM(t.pnl) AS total_pnl,
               COUNT(*) FILTER (WHERE t.pnl > 0)::integer AS wins
        FROM trades t
        ${baseWhere}
        GROUP BY 1
      `, params),
      db.query(`
        SELECT EXTRACT(HOUR FROM t.entry_time)::integer AS name,
               COUNT(*)::integer AS trades,
               SUM(t.pnl) AS total_pnl,
               COUNT(*) FILTER (WHERE t.pnl > 0)::integer AS wins
        FROM trades t
        ${baseWhere}
          AND t.entry_time IS NOT NULL
        GROUP BY 1
      `, params)
    ]);

    const normalize = (rows, type) => (rows || []).map(row => {
      const trades = parseInt(row.trades) || 0;
      const wins = parseInt(row.wins) || 0;
      return {
        type,
        name: type === 'time_of_day' ? formatHourLabel(row.name) : String(row.name),
        trades,
        wins,
        win_rate: trades > 0 ? round2((wins / trades) * 100) : 0,
        total_pnl: round2(row.total_pnl)
      };
    });

    return {
      strategies: normalize(strategyResult.rows, 'strategy'),
      symbols: normalize(symbolResult.rows, 'symbol'),
      hours: normalize(hourResult.rows, 'time_of_day')
    };
  }

  // Best-performing group across strategy / symbol / time-of-day.
  // Prefers groups with at least MIN_GROUP_TRADES trades so a single lucky
  // trade is not declared "your edge"; falls back to single-trade groups.
  static pickEdge(dimensions) {
    const all = [
      ...dimensions.strategies.filter(d => d.name !== 'unspecified'),
      ...dimensions.symbols,
      ...dimensions.hours
    ].filter(d => d.total_pnl > 0);

    if (all.length === 0) return null;

    const meaningful = all.filter(d => d.trades >= MIN_GROUP_TRADES);
    const pool = meaningful.length > 0 ? meaningful : all;
    const best = pool.reduce((acc, d) => (d.total_pnl > acc.total_pnl ? d : acc));

    return {
      type: best.type,
      name: best.name,
      trades: best.trades,
      win_rate: best.win_rate,
      total_pnl: best.total_pnl
    };
  }

  // Longest run of consecutive losing trades within the week.
  static computeLossStreak(recentTradePnls) {
    let longest = 0;
    let current = 0;
    let currentLoss = 0;
    let longestLoss = 0;
    for (const row of recentTradePnls || []) {
      const pnl = parseFloat(row.pnl);
      if (Number.isFinite(pnl) && pnl < 0) {
        current++;
        currentLoss += pnl;
        if (current > longest) {
          longest = current;
          longestLoss = currentLoss;
        }
      } else {
        current = 0;
        currentLoss = 0;
      }
    }
    return { length: longest, total_pnl: round2(longestLoss) };
  }

  // Worst pattern of the week, picked deterministically by dollar impact.
  static pickLeak(dimensions, weekSummary, lossStreak) {
    const candidates = [];

    const worstOf = (rows) => rows
      .filter(d => d.total_pnl < 0)
      .reduce((acc, d) => (!acc || d.total_pnl < acc.total_pnl ? d : acc), null);

    const worstSymbol = worstOf(dimensions.symbols);
    if (worstSymbol) {
      candidates.push({
        type: 'symbol',
        name: worstSymbol.name,
        trades: worstSymbol.trades,
        total_pnl: worstSymbol.total_pnl,
        impact: Math.abs(worstSymbol.total_pnl),
        description: `${worstSymbol.name} cost ${formatMoney(worstSymbol.total_pnl)} across ${worstSymbol.trades} trade${worstSymbol.trades === 1 ? '' : 's'} this week.`
      });
    }

    const worstStrategy = worstOf(dimensions.strategies.filter(d => d.name !== 'unspecified'));
    if (worstStrategy) {
      candidates.push({
        type: 'strategy',
        name: worstStrategy.name,
        trades: worstStrategy.trades,
        total_pnl: worstStrategy.total_pnl,
        impact: Math.abs(worstStrategy.total_pnl),
        description: `The ${worstStrategy.name} strategy lost ${formatMoney(Math.abs(worstStrategy.total_pnl))} over ${worstStrategy.trades} trade${worstStrategy.trades === 1 ? '' : 's'}.`
      });
    }

    const avgWin = weekSummary.avg_win;
    const avgLoss = Math.abs(weekSummary.avg_loss);
    if (weekSummary.losing_trades >= MIN_GROUP_TRADES && avgWin > 0 && avgLoss > avgWin * OVERSIZED_LOSER_RATIO) {
      candidates.push({
        type: 'oversized_losses',
        name: 'average loser larger than average winner',
        trades: weekSummary.losing_trades,
        total_pnl: round2(-avgLoss * weekSummary.losing_trades),
        impact: avgLoss * weekSummary.losing_trades,
        description: `Your average loser (${formatMoney(-avgLoss)}) is ${round2(avgLoss / avgWin)}x your average winner (${formatMoney(avgWin)}).`
      });
    }

    if (lossStreak.length >= LOSS_STREAK_THRESHOLD) {
      candidates.push({
        type: 'loss_streak',
        name: `${lossStreak.length} consecutive losses`,
        trades: lossStreak.length,
        total_pnl: lossStreak.total_pnl,
        impact: Math.abs(lossStreak.total_pnl),
        description: `You took ${lossStreak.length} losses in a row costing ${formatMoney(Math.abs(lossStreak.total_pnl))}.`
      });
    }

    if (candidates.length === 0) return null;

    const worst = candidates.reduce((acc, c) => (c.impact > acc.impact ? c : acc));
    const { impact, ...leak } = worst;
    return leak;
  }

  // One concrete action item derived deterministically from the worst leak.
  static deriveActionItem(leak, weekSummary) {
    if (!leak) {
      if (weekSummary.total_pnl >= 0) {
        return 'No major leak detected this week. Keep position sizing consistent and log every trade so next week\'s report stays accurate.';
      }
      return 'No single leak stood out, but the week was net negative. Review your losing trades for a common thread before sizing up.';
    }

    switch (leak.type) {
      case 'symbol':
        return `Cut size in ${leak.name} or sit it out next week. It was your most expensive symbol at ${formatMoney(leak.total_pnl)}.`;
      case 'strategy':
        return `Pause or paper-trade the ${leak.name} strategy next week until you identify what is failing. It cost ${formatMoney(Math.abs(leak.total_pnl))} this week.`;
      case 'oversized_losses':
        return `Tighten your stops: cap each loss at no more than your average winner (${formatMoney(weekSummary.avg_win)}) until your loss size comes back in line.`;
      case 'loss_streak':
        return `Add a circuit breaker: after two consecutive losses, stop trading for the day. Your worst streak this week ran ${leak.trades} trades.`;
      default:
        return 'Review your largest losing trades from this week and write down the single rule that would have avoided them.';
    }
  }

  static async getPlaybookSection(userId) {
    try {
      const Playbook = require('../models/Playbook');
      const analytics = await Playbook.getAnalytics(userId);
      const overview = analytics?.overview;
      if (!overview || !parseInt(overview.playbook_count)) return null;
      return {
        playbook_count: parseInt(overview.playbook_count) || 0,
        reviewed_trade_count: parseInt(overview.reviewed_trade_count) || 0,
        followed_trade_count: parseInt(overview.followed_trade_count) || 0,
        broken_trade_count: parseInt(overview.broken_trade_count) || 0,
        adherence_average: round2(overview.adherence_average)
      };
    } catch (error) {
      console.warn('[EDGE-REPORT] Playbook section unavailable:', error.message);
      return null;
    }
  }

  static getBestWorstDay(dailyPnL) {
    let best = null;
    let worst = null;
    for (const row of dailyPnL || []) {
      const pnl = round2(row.daily_pnl);
      const date = row.trade_date instanceof Date ? toDateString(row.trade_date) : String(row.trade_date);
      if (!best || pnl > best.pnl) best = { date, pnl };
      if (!worst || pnl < worst.pnl) worst = { date, pnl };
    }
    return { best_day: best, worst_day: worst };
  }

  // Builds the structured snake_case report. Returns null for zero-trade weeks.
  static async buildReport(userId, { periodStart, periodEnd }) {
    const current = await TradeQueries.getAnalytics(userId, {
      startDate: periodStart,
      endDate: periodEnd
    });

    const week = this.summarizeAnalytics(current);
    if (week.total_trades === 0) {
      return null;
    }

    const prevEnd = shiftDays(periodStart, -1);
    const prevStart = shiftDays(periodStart, -7);
    let previousWeek = null;
    try {
      const previous = await TradeQueries.getAnalytics(userId, {
        startDate: prevStart,
        endDate: prevEnd
      });
      previousWeek = this.summarizeAnalytics(previous);
    } catch (error) {
      console.warn('[EDGE-REPORT] Comparison period unavailable:', error.message);
    }

    const dimensions = await this.getDimensionStats(userId, periodStart, periodEnd);
    const lossStreak = this.computeLossStreak(current.recentTradePnls);
    const edge = this.pickEdge(dimensions);
    const leak = this.pickLeak(dimensions, week, lossStreak);
    const actionItem = this.deriveActionItem(leak, week);
    const playbook = await this.getPlaybookSection(userId);
    const { best_day, worst_day } = this.getBestWorstDay(current.dailyPnL);

    return {
      period_start: periodStart,
      period_end: periodEnd,
      week: {
        ...week,
        best_day,
        worst_day
      },
      previous_week: previousWeek,
      deltas: previousWeek ? {
        total_trades: week.total_trades - previousWeek.total_trades,
        win_rate: round2(week.win_rate - previousWeek.win_rate),
        total_pnl: round2(week.total_pnl - previousWeek.total_pnl),
        profit_factor: round2(week.profit_factor - previousWeek.profit_factor)
      } : null,
      edge,
      leak,
      playbook,
      action_item: actionItem
    };
  }

  static buildNarrativePrompt(report) {
    return `You are a calm, direct trading coach. Using ONLY the structured weekly report below, write a short plain-text coaching summary for the trader. Max 200 words. No emojis. No hype. No markdown, no bullet points, no headings. Do not give financial advice or predict markets. Mention the week's results, the edge (if any), the leak (if any), and end by reinforcing the action item.

Weekly report (JSON):
${JSON.stringify(report, null, 2)}

Write the coaching summary now.`;
  }

  // Deterministic narrative used when AI is not configured or fails.
  static buildFallbackNarrative(report) {
    const parts = [];
    const week = report.week;
    parts.push(`You closed ${week.total_trades} trade${week.total_trades === 1 ? '' : 's'} this week for ${formatMoney(week.total_pnl)} with a ${week.win_rate.toFixed(1)}% win rate.`);

    if (report.previous_week && report.previous_week.total_trades > 0) {
      const diff = report.deltas?.total_pnl ?? 0;
      const direction = diff >= 0 ? 'up' : 'down';
      parts.push(`That is ${direction} ${formatMoney(Math.abs(diff))} versus the prior week.`);
    }

    if (report.edge) {
      const label = report.edge.type === 'time_of_day'
        ? `trading around ${report.edge.name}`
        : `${report.edge.name} (${report.edge.type})`;
      parts.push(`Your edge: ${label} produced ${formatMoney(report.edge.total_pnl)} across ${report.edge.trades} trade${report.edge.trades === 1 ? '' : 's'} at a ${report.edge.win_rate.toFixed(1)}% win rate.`);
    }

    if (report.leak) {
      parts.push(`Your leak: ${report.leak.description}`);
    }

    parts.push(`Action for next week: ${report.action_item}`);
    return parts.join(' ');
  }

  // Narrative via the user's configured AI provider; never throws.
  static async generateNarrative(userId, report) {
    const fallback = this.buildFallbackNarrative(report);
    try {
      const settings = await AIService.getUserSettings(userId);
      if (!AIService.isProviderConfigured(settings)) {
        return fallback;
      }
      const text = await AIService.generateResponse(userId, this.buildNarrativePrompt(report), {
        maxTokens: 400
      });
      if (typeof text !== 'string' || !text.trim()) {
        return fallback;
      }
      return text.trim();
    } catch (error) {
      console.warn('[EDGE-REPORT] AI narrative failed, using fallback:', error.message);
      return fallback;
    }
  }

  static async findExisting(userId, periodStart) {
    const result = await db.query(
      `SELECT * FROM edge_reports WHERE user_id = $1 AND period_start = $2`,
      [userId, periodStart]
    );
    return result.rows[0] || null;
  }

  // Builds, persists (upsert on user_id + period_start), emails when the user
  // opted in and email is configured. Returns the stored row, or null for a
  // zero-trade week.
  static async generateForUser(userId, { force = false, periodStart, periodEnd } = {}) {
    if (!periodStart || !periodEnd) {
      const period = this.getDefaultPeriod();
      periodStart = periodStart || period.periodStart;
      periodEnd = periodEnd || period.periodEnd;
    }

    if (!force) {
      const existing = await this.findExisting(userId, periodStart);
      if (existing) {
        return existing;
      }
    }

    const report = await this.buildReport(userId, { periodStart, periodEnd });
    if (!report) {
      console.log(`[EDGE-REPORT] No trades for user ${userId} between ${periodStart} and ${periodEnd}, skipping report`);
      return null;
    }

    const narrative = await this.generateNarrative(userId, report);

    const result = await db.query(
      `INSERT INTO edge_reports (user_id, period_start, period_end, report, narrative)
       VALUES ($1, $2, $3, $4::jsonb, $5)
       ON CONFLICT (user_id, period_start)
       DO UPDATE SET
         period_end = EXCLUDED.period_end,
         report = EXCLUDED.report,
         narrative = EXCLUDED.narrative,
         created_at = NOW()
       RETURNING *`,
      [userId, periodStart, periodEnd, JSON.stringify(report), narrative]
    );
    const row = result.rows[0];

    await this.maybeSendEmail(userId, report, narrative);

    return row;
  }

  // Email is best-effort: skipped silently when not opted in or not
  // configured, and a send failure never fails report generation.
  static async maybeSendEmail(userId, report, narrative) {
    try {
      const settings = await User.getSettings(userId);
      if (!settings || settings.edge_report_enabled !== true) {
        return false;
      }
      if (!EmailService.isConfigured()) {
        console.log('[EDGE-REPORT] Email not configured, skipping edge report email');
        return false;
      }
      const user = await User.findById(userId);
      if (!user || !user.email) {
        return false;
      }
      await EmailService.sendEdgeReportEmail(user, report, narrative);
      return true;
    } catch (error) {
      console.error(`[EDGE-REPORT] Failed to send edge report email for user ${userId}:`, error.message);
      return false;
    }
  }

  // Weekly batch over all opted-in users. Per-user failures are isolated.
  static async runWeeklyBatch() {
    const stats = { users: 0, generated: 0, skipped: 0, failed: 0 };
    let users;
    try {
      const result = await db.query(`
        SELECT u.id
        FROM users u
        INNER JOIN user_settings s ON s.user_id = u.id
        WHERE s.edge_report_enabled = true
        ORDER BY u.id
      `);
      users = result.rows;
    } catch (error) {
      console.error('[EDGE-REPORT] Failed to load opted-in users:', error.message);
      throw error;
    }

    stats.users = users.length;
    console.log(`[EDGE-REPORT] Weekly batch starting for ${users.length} user(s)`);

    for (const user of users) {
      try {
        const row = await this.generateForUser(user.id, { force: true });
        if (row) {
          stats.generated++;
        } else {
          stats.skipped++;
        }
      } catch (error) {
        stats.failed++;
        console.error(`[EDGE-REPORT] Failed to generate report for user ${user.id}:`, error.message);
      }
    }

    console.log(`[EDGE-REPORT] Weekly batch complete: ${stats.generated} generated, ${stats.skipped} skipped (no trades), ${stats.failed} failed`);
    return stats;
  }

  static async listForUser(userId, limit = 12) {
    const result = await db.query(
      `SELECT id, period_start, period_end, report, narrative, created_at
       FROM edge_reports
       WHERE user_id = $1
       ORDER BY period_start DESC
       LIMIT $2`,
      [userId, limit]
    );
    return result.rows;
  }

  static async getLatestForUser(userId) {
    const rows = await this.listForUser(userId, 1);
    return rows[0] || null;
  }
}

module.exports = EdgeReportService;
